language: php
php:
  - '7.0'
before_install: 'echo "{\"http-basic\":{\"repo.magento.com\":{\"username\": \"$MAGENTO_PUBLIC_KEY\", \"password\": \"$MAGENTO_PRIVATE_KEY\"}}}" > ~/.composer/auth.json'
install: composer install
script: composer run ci